on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push to main branch
jobs:
  web-deploy:
    name: 🎉 Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          npm install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: api.enterviews.gospelchukwu.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/api.enterviews.gospelchukwu.com/
